name: Valitation
on: workflow_dispatch
jobs:
  Validate:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run action
        id: yamllint
        uses: jacobtomlinson/gha-lint-yaml@master
        with:
          path: 'subscriptions.yml'
          
      - name: Check outputs
        run: |
           echo "There were ${{ steps.yamllint.outputs.warnings }} YAML linting warnings."
       
      - name: Get last user
        run: |
          # Get the value of the `user` field from the last line of subscriptions.yml
          LAST_USER=$(grep -E "^\s+- user:" subscriptions.yml | awk '{print $3}' | tail -n1)
          # Set an environment variable for the last user
          echo "LAST_USER=$LAST_USER" >> $GITHUB_ENV
          echo "last user is ${LAST_USER}"
        
